import type {Metadata} from 'next';
import {LegalTerms} from "@/components/screens/frontend/main/LegalTerms";

;

export const metadata: Metadata = {
  title: 'Zberezhemo - Legal terms',
  description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode; }>) {
  return (
      <>
          <LegalTerms />
      </>
  );
}
