import { LegalTerms } from '@/components/screens';
// import type { Metadata } from 'next';

// export const metadata: Metadata = {
//   title: 'Zberezhemo - Legal terms',
//   description: 'Generated by create next app',
// };

export default function PageLegalTerms() {
  return (
    <>
      <LegalTerms />
    </>
  );
}
