import { LegalTerms } from '@/components/screens/frontend/main/LegalTerms';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Zberezhemo - Legal terms',
  description: 'Generated by create next app',
};

export default function RootLayout() {
  return (
    <>
      <LegalTerms />
    </>
  );
}
