import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import {Header, Footer} from '@/components';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Zberezhemo',
  description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
  return (
    <>
      <Header/>
      <main className="flex min-h-screen flex-col items-center justify-between p-24">
        {children}
      </main>
      <Footer/>
    </>
  );
}
